resources:
  - non_cache.yaml
  - ingress.yaml
  - postgres_deployment.yml
patches:
  - path: deployment-patch.yaml
    target:
      group: apps
      version: v1
      kind: Deployment
      name: non-cache-deployment
