dbHost = "postgres-service"
dbUsername = "postgres"
dbPassword = "postgres"
dbName = "postgres"
dbPort = 5432
# Change the cache configurations if need.
capacity = 100
evictionFactor = 0.2
defaultMaxAge = 120.0
cleanupInterval = 5.0