[package]
org = "ballerinax"
name = "java.jdbc"
version = "1.0.1"
distribution = "slbeta3"

[[platform.java11.dependency]]
path = "../native/build/libs/java.jdbc-native-1.0.1-SNAPSHOT.jar"

[[platform.java11.dependency]]
path = "./lib/sql-native-1.0.0.jar"
