[package]
org = "ballerinax"
name = "java.jdbc"
version = "1.0.0"
distribution = "slbeta3"

[[platform.java11.dependency]]
path = "../native/build/libs/java.jdbc-native-1.0.0-SNAPSHOT.jar"

[[platform.java11.dependency]]
path = "./lib/sql-native-1.0.0-20211008-021900-95abc84.jar"
