[package]
org = "ballerinax"
name = "java.jdbc"
version = "1.10.1"
authors = ["Ballerina"]
keywords = ["database", "client", "network", "SQL", "RDBMS", "JDBC"]
repository = "https://github.com/ballerina-platform/module-ballerinax-java.jdbc"
icon = "icon.png"
license = ["Apache-2.0"]
distribution = "2201.7.0"

[platform.java17]
graalvmCompatible = true

[[platform.java17.dependency]]
groupId = "io.ballerina.stdlib"
artifactId = "java.jdbc-native"
version = "1.10.1"
path = "../native/build/libs/java.jdbc-native-1.10.1-SNAPSHOT.jar"

[[platform.java17.dependency]]
groupId = "io.ballerina.stdlib"
artifactId = "sql-native"
version = "1.10.0"
path = "./lib/sql-native-1.10.0.jar"

[[platform.java17.dependency]]
path = "./lib/h2-@h2.connector.version@.jar"
scope = "testOnly"

[[platform.java17.dependency]]
path = "../native-image-configs/build/libs/java.jdbc-native-image-configs-1.10.1-SNAPSHOT.jar"
scope = "testOnly"
