resources:
  - cache_with_cleanup_task.yaml
  - ingress.yaml
  - postgres_deployment.yml
patches:
  - path: deployment-patch.yaml
    target:
      group: apps
      version: v1
      kind: Deployment
      name: cache-deployment
