[package]
org = "ballerina"
name = "java.jdbc"
version = "@toml.version@"

[[dependency]]
org = "ballerina"
name = "sql"
version = "@stdlib.sql.version@"

[[platform.java11.dependency]]
path = "../java.jdbc-native/build/libs/java.jdbc-native-@project.version@.jar"
groupId = "org.ballerinalang"
artifactId = "jdbc"
version = "@project.version@"

[[platform.java11.dependency]]
path = "@project.path@/bre/lib/sql-native-@stdlib.sql.native.version@.jar"
groupId = "org.ballerinalang"
artifactId = "sql-native"
version = "@stdlib.sql.native.version@"
