[project]
org-name = "ballerina"
version = "@toml.version@"

[platform]
target = "java11"

[dependencies]
"ballerina/sql" = "@stdlib.sql.version@"

    [[platform.libraries]]
    artifactId = "jdbc"
    version = "@project.version@"
    path = "../java.jdbc-native/build/libs/java.jdbc-native-@project.version@.jar"
    groupId = "org.ballerinalang"
    modules = ["java.jdbc"]

    [[platform.libraries]]
    artifactId = "sql-native"
    version = "@stdlib.sql.native.version@"
    path = "@project.path@/bre/lib/sql-native-@stdlib.sql.native.version@.jar"
    groupId = "org.ballerinalang"
    modules = ["java.jdbc"]
