[project]
org-name = "ballerina"
version = "@toml.version@"

[platform]
target = "java8"

    [[platform.libraries]]
    artifactId = "jdbc"
    version = "0.5.0"
    path = "../java.jdbc-native/build/libs/java.jdbc-native-@project.version@.jar"
    groupId = "org.ballerinalang"
    modules = ["java.jdbc"]

    [[platform.libraries]]
    artifactId = "ballerina-sql"
    version = "0.5.0"
    path = "@project.path@/bre/lib/ballerina-sql-0.5.0-java.jar"
    groupId = "org.ballerinalang"
    modules = ["java.jdbc"]
