[package]
org = "ballerina"
name = "jdbc"
version = "@toml.version@"

[[platform.java11.dependency]]
path = "../java.jdbc-native/build/libs/java.jdbc-native-@project.version@.jar"
groupId = "org.ballerinalang"
artifactId = "jdbc"
version = "@project.version@"

[[platform.java11.dependency]]
path = "@project.path@/repo/balo/ballerina/sql/@stdlib.sql.version@/platform/java11/sql-native-@stdlib.sql.native.version@.jar"
groupId = "org.ballerinalang"
artifactId = "sql-native"
version = "@stdlib.sql.native.version@"
