[project]
org-name = "ballerina"
version = "@toml.version@"

[platform]
target = "java8"

[dependencies]
"ballerina/sql" = "@stdlib.sql.version@"
"ballerina/io" = "@stdlib.io.version@"
"ballerina/time" = "@stdlib.time.version@"
"ballerina/stringutils" = "@stdlib.stringutils.version@"
"ballerina/filepath" = "@stdlib.filepath.version@"
"ballerina/runtime" = "@stdlib.runtime.version@"
"ballerina/system" = "@stdlib.system.version@"
"ballerina/log" = "@stdlib.log.version@"
"ballerina/config" = "@stdlib.config.version@"

    [[platform.libraries]]
    artifactId = "jdbc"
    version = "@project.version@"
    path = "../java.jdbc-native/build/libs/java.jdbc-native-@project.version@.jar"
    groupId = "org.ballerinalang"
    modules = ["java.jdbc"]

    [[platform.libraries]]
    artifactId = "sql-native"
    version = "@stdlib.sql.native.version@"
    path = "@project.path@/bre/lib/sql-native-@stdlib.sql.native.version@.jar"
    groupId = "org.ballerinalang"
    modules = ["java.jdbc"]
